### ISSUE TITLE
Quality of master branch

### ISSUE THREAD

**Issue by hannesa2** [Sternbach-Software/GeniForAndroid#15]
Just for your info, I did a short test of your master branch. I run immediate into
```
    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.familygem/app.familygem.ProfileActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
        at app.familygem.ProfileActivity.onCreate(ProfileActivity.java:79)
```
Doing this big refactoring without a CI, which at least starts each activity is a no go. It introduces too much errors.
I at least started to make Espresso tests during pull requests to avoid this. 

To be honest, that's why I can't base my fork on this repo

**Comment by hannesa2** [comment]
Interesting to see Kotlin works without these changes
<img width="814" alt="image" src="https://user-images.githubusercontent.com/3314607/204490245-6ee9df9c-d4d1-42f6-8eb1-be186ab3df6b.png">

<img width="825" alt="image" src="https://user-images.githubusercontent.com/3314607/204490280-1769cbdd-86d6-4b6e-95cb-a9ec21dd114d.png">

If you do so, you'll run into tons of errors

<img width="493" alt="image" src="https://user-images.githubusercontent.com/3314607/204490510-3b28cd24-6de9-4697-b0cd-03abc1981388.png">

Btw, `.gitignore` is broken now
